sudo: false
language: php node_js
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7
- hhvm
node_js:
- "6"
- "5"
- "4"
- "0.1"
script:
- ".travis-build/phplint ."
- phpunit
after_script:
- vendor/bin/test-reporter
addons:
  code_climate:
    repo_token: 3060bdda5db8f779d82ab527acadec5cd581bde782093136322604a4280162e7
notifications: 
deploy:
  provider: releases
  api_key:
    secure: lPFLb25Gwb/X8aBiNQ4Mz2b5XBviLLg0Zp7Rgoj9Xc8ZwFlNw/JqnoLKnZFljXBW38yUt3fEyxUGFrImLDbwwzN6+1iOfjVrCrIYdJtKf1CoF9Mq1+bjUbz8wIXfvdIvuF+VxFWFcbFtUiTiVpeDkSBwWXLaazCZWQJZpWYZuQc=
  file: InternshipInventory*release*.tar.gz
  on:
    repo: eberhardtm/InternshipInventory
    tags: true